import { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import {
    prepareSimulation,
    getPrepareStatus,
    getSimulationProfilesRealtime,
    getSimulationConfig,
    getSimulationConfigRealtime,
} from '../../api/simulation';
import useProcessStore from '../../store/useProcessStore';
import './Step2EnvSetup.css';

const Step2EnvSetup = ({
    simulationId,
    projectData,
    systemLogs = [],
    onGoBack,
    onNextStep,
    onAddLog,
    onUpdateStatus,
}) => {
    const updateSession = useProcessStore((state) => state.updateSession);
    const getSession = useProcessStore((state) => state.getSession);

    const [phase, setPhase] = useState(0); // 0: 初始化, 1: 生成人设, 2: 生成配置, 3: 初始激活编排, 4: 完成
    const [taskId, setTaskId] = useState(null);
    const [prepareProgress, setPrepareProgress] = useState(0);
    const [currentStage, setCurrentStage] = useState('');
    const [progressMessage, setProgressMessage] = useState('');
    const [profiles, setProfiles] = useState([]);
    const [expectedTotal, setExpectedTotal] = useState(null);
    const [simulationConfig, setSimulationConfig] = useState(null);
    const [selectedProfile, setSelectedProfile] = useState(null);
    const [isPaused, setIsPaused] = useState(false); // 控制是否属于暂停状态
    const [isAborted, setIsAborted] = useState(false); // 标记是否被硬阻断或手工中止

    // 轮数配置
    const [useCustomRounds, setUseCustomRounds] = useState(false);
    const [customMaxRounds, setCustomMaxRounds] = useState(40);

    const logContentRef = useRef(null);
    const pollTimerRef = useRef(null);
    const profilesTimerRef = useRef(null);
    const configTimerRef = useRef(null);
    const pollCountRef = useRef(0);

    // 记录上次输出的日志维度
    const lastLoggedRef = useRef({ msg: '', count: 0, configStage: '' });

    // Sync state to persistent store
    useEffect(() => {
        if (simulationId) {
            updateSession(simulationId, {
                step2: {
                    taskId,
                    phase,
                    prepareProgress,
                    currentStage,
                    progressMessage,
                    profiles,
                    expectedTotal,
                    config: simulationConfig,
                    customRounds: { useCustom: useCustomRounds, maxRounds: customMaxRounds },
                    isPaused,
                    isAborted,
                },
            });
        }
    }, [
        simulationId,
        taskId,
        phase,
        prepareProgress,
        currentStage,
        progressMessage,
        profiles,
        expectedTotal,
        simulationConfig,
        useCustomRounds,
        customMaxRounds,
        isPaused,
        isAborted,
        updateSession,
    ]);

    // 自动生成的轮数计算
    const autoGeneratedRounds = useMemo(() => {
        if (!simulationConfig?.time_config) return null;
        const { total_simulation_hours, minutes_per_round } = simulationConfig.time_config;
        if (!total_simulation_hours || !minutes_per_round) return null;
        return Math.max(Math.floor((total_simulation_hours * 60) / minutes_per_round), 40);
    }, [simulationConfig]);

    const totalTopicsCount = useMemo(() => {
        return profiles.reduce((sum, p) => sum + (p.interested_topics?.length || 0), 0);
    }, [profiles]);

    const addLog = useCallback(
        (msg) => {
            onAddLog && onAddLog(msg);
        },
        [onAddLog]
    );

    // Stage changes -> Phase sync
    // Moved to bottom to avoid TDZ issues

    const handleStartSimulation = () => {
        const params = {};
        if (useCustomRounds) {
            params.maxRounds = customMaxRounds;
            addLog(`开始模拟，自定义轮数: ${customMaxRounds} 轮`);
        } else {
            addLog(`开始模拟，使用自动配置轮数: ${autoGeneratedRounds} 轮`);
        }
        onNextStep && onNextStep(params);
    };

    const startPrepareSimulation = async () => {
        if (!simulationId) {
            addLog('错误：缺少 simulationId');
            onUpdateStatus && onUpdateStatus('error');
            return;
        }

        // Check for existing session to restore
        const session = getSession(simulationId);
        if (session?.step2?.taskId) {
            const s2 = session.step2;
            addLog(`[恢复] 检测到本地未完成任务，正在恢复状态... (TaskID: ${s2.taskId})`);

            setTaskId(s2.taskId);
            if (s2.phase !== undefined) setPhase(s2.phase);
            if (s2.profiles) setProfiles(s2.profiles);
            if (s2.expectedTotal) setExpectedTotal(s2.expectedTotal);
            if (s2.config) setSimulationConfig(s2.config);
            if (s2.customRounds) {
                setUseCustomRounds(s2.customRounds.useCustom);
                setCustomMaxRounds(s2.customRounds.maxRounds);
            }
            if (s2.isPaused) setIsPaused(true);
            if (s2.isAborted) setIsAborted(true);

            // Resume polling if needed
            if (s2.phase < 4 && !s2.isPaused && !s2.isAborted) {
                startPolling(s2.taskId);
                startProfilesPolling();
                if (s2.phase >= 2) startConfigPolling();
            } else if (s2.phase === 4) {
                addLog('任务已标记为完成');
                onUpdateStatus && onUpdateStatus('success');
            }
            return;
        }

        setPhase(1);
        addLog(`模拟实例已创建: ${simulationId}`);
        addLog('正在准备模拟环境...');
        onUpdateStatus && onUpdateStatus('processing');

        try {
            const res = await prepareSimulation({
                simulation_id: simulationId,
                use_llm_for_profiles: true,
                parallel_profile_count: 5,
            });

            if (res.success && res.data) {
                if (res.data.already_prepared) {
                    addLog('检测到已有完成的准备工作，直接使用');
                    await loadPreparedData();
                    return;
                }

                setTaskId(res.data.task_id);
                addLog(`准备任务已启动`);
                addLog(`  └─ Task ID: ${res.data.task_id}`);

                if (res.data.expected_entities_count || res.data.expected_total_profiles) {
                    setExpectedTotal(
                        res.data.expected_entities_count || res.data.expected_total_profiles
                    );
                }

                startPolling(res.data.task_id);
                startProfilesPolling();
            } else {
                addLog(`启动失败: ${res.error || '未知错误'}`);
                onUpdateStatus && onUpdateStatus('error');
            }
        } catch (err) {
            addLog(`启动异常: ${err.message}`);
            onUpdateStatus && onUpdateStatus('error');
        }
    };

    const loadPreparedData = async () => {
        try {
            const configRes = await getSimulationConfig(simulationId);
            if (configRes.success && configRes.data) {
                setSimulationConfig(configRes.data);
                if (configRes.data.agent_configs?.length) {
                    setProfiles(configRes.data.agent_configs);
                    setExpectedTotal(configRes.data.agent_configs.length);
                }
            }
            setPhase(4);
            setPrepareProgress(100);
            setCurrentStage('完成');
            addLog('环境准备已就绪');
            onUpdateStatus && onUpdateStatus('success');
        } catch (err) {
            addLog('加载已有配置失败: ' + err.message);
        }
    };

    // Pollings
    const startPolling = (taskIdParam) => {
        if (pollTimerRef.current) clearInterval(pollTimerRef.current);
        pollCountRef.current = 0;
        setIsPaused(false);
        setIsAborted(false);
        pollTimerRef.current = setInterval(() => checkStatus(taskIdParam), 2000);
    };
    const stopPolling = () => {
        if (pollTimerRef.current) {
            clearInterval(pollTimerRef.current);
            pollTimerRef.current = null;
        }
    };

    const startProfilesPolling = () => {
        if (profilesTimerRef.current) clearInterval(profilesTimerRef.current);
        profilesTimerRef.current = setInterval(fetchProfiles, 3000);
    };
    const stopProfilesPolling = () => {
        if (profilesTimerRef.current) {
            clearInterval(profilesTimerRef.current);
            profilesTimerRef.current = null;
        }
    };

    const startConfigPolling = () => {
        if (configTimerRef.current) clearInterval(configTimerRef.current);
        configTimerRef.current = setInterval(fetchConfigProgress, 3000);
    };
    const stopConfigPolling = () => {
        if (configTimerRef.current) {
            clearInterval(configTimerRef.current);
            configTimerRef.current = null;
        }
    };

    const checkStatus = async (tid) => {
        if (!tid) return;
        try {
            const res = await getPrepareStatus({ task_id: tid, simulation_id: simulationId });
            if (res.success && res.data) {
                const { progress, stage, message, status, result } = res.data;
                setPrepareProgress(progress || 0);
                if (stage) setCurrentStage(stage);
                if (message) setProgressMessage(message);

                if (message && message !== lastLoggedRef.current.msg) {
                    addLog(`[准备过程] ${message}`);
                    lastLoggedRef.current.msg = message;
                }
                if (res.data.expected_total_profiles || res.data.expected_entities_count) {
                    setExpectedTotal(
                        res.data.expected_total_profiles || res.data.expected_entities_count
                    );
                }

                pollCountRef.current += 1;
                // 硬阻断：防止因未知 Bug 导致的无限轮询浪费服务器资源 (例如 600 次大约为 20 分钟卡死)
                if (pollCountRef.current > 600 && status !== 'completed' && status !== 'ready') {
                    handleAbort('检测到状态查询超过最大重试次数，已强制阻断以防资源浪费。');
                    return;
                }

                if (status === 'completed' || status === 'ready') {
                    stopPolling();
                    stopProfilesPolling();
                    stopConfigPolling();
                    setIsPaused(false);
                    setPhase(4);
                    addLog('✓ 环境准备全部完成');
                    onUpdateStatus && onUpdateStatus('success');
                    if (result || res.data.already_prepared) {
                        await fetchProfiles();
                        await fetchConfigProgress(true);
                    }
                } else if (status === 'failed') {
                    stopPolling();
                    stopProfilesPolling();
                    stopConfigPolling();
                    addLog(`✗ 准备失败: ${res.data.error || '任务中止'}`);
                    onUpdateStatus && onUpdateStatus('error');
                }
            }
        } catch (err) {
            console.warn('获取状态异常:', err);
        }
    };

    const fetchProfiles = async () => {
        try {
            const res = await getSimulationProfilesRealtime(simulationId);
            if (res.success && res.data) {
                setProfiles(res.data.profiles || []);
                setExpectedTotal(res.data.expected_total || expectedTotal);

                const currentCount = res.data.profiles?.length || 0;
                if (currentCount > lastLoggedRef.current.count && currentCount % 5 === 0) {
                    addLog(`已生成人设: ${currentCount}/${res.data.expected_total || '未知'}...`);
                    lastLoggedRef.current.count = currentCount;
                }
            }
        } catch {
            /* ignore */
        }
    };

    const fetchConfigProgress = async (isFinal = false) => {
        try {
            const method = isFinal ? getSimulationConfig : getSimulationConfigRealtime;
            const res = await method(simulationId);
            if (res.success && res.data) {
                const cfg = isFinal ? res.data : res.data.config_preview;
                if (cfg && Object.keys(cfg).length > 0) {
                    setSimulationConfig(cfg);
                    const stage = res.data.stage || '';
                    if (stage && stage !== lastLoggedRef.current.configStage) {
                        addLog(`配置进度: 生成${stage}...`);
                        lastLoggedRef.current.configStage = stage;
                    }
                }
            }
        } catch {
            /* ignore */
        }
    };

    const handlePause = () => {
        setIsPaused(true);
        stopPolling();
        stopProfilesPolling();
        stopConfigPolling();
        addLog('⏸ 准备过程已暂停轮询');
    };

    const handleResume = () => {
        if (taskId) {
            startPolling(taskId);
            startProfilesPolling();
            if (phase >= 2) startConfigPolling();
            addLog('▶ 准备过程已恢复轮询');
        }
    };

    const handleAbort = (msg) => {
        stopPolling();
        stopProfilesPolling();
        stopConfigPolling();
        setIsAborted(true);
        addLog(`🛑 准备过程已中止/回退: ${msg}`);
        onUpdateStatus && onUpdateStatus('error');
    };

    const handleRetry = () => {
        addLog('🔄 重新发起环境准备请求...');
        // Clear session to force restart
        if (simulationId) {
            const currentSession = getSession(simulationId);
            if (currentSession?.step2) {
                const newSession = { ...currentSession };
                delete newSession.step2;
                updateSession(simulationId, newSession);
            }
        }

        setIsAborted(false);
        setIsPaused(false);
        setPhase(0);
        setProfiles([]);
        setSimulationConfig(null);
        startPrepareSimulation();
    };

    useEffect(() => {
        addLog('Step2 环境搭建初始化');
        if (simulationId) {
            // Avoid synchronous state update warning
            setTimeout(() => startPrepareSimulation(), 0);
        }
        return () => {
            stopPolling();
            stopProfilesPolling();
            stopConfigPolling();
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [simulationId]);

    // Stage changes -> Phase sync (Moved from top)
    useEffect(() => {
        if (currentStage === '生成Agent人设' || currentStage === 'generating_profiles') {
            setPhase(1);
        } else if (currentStage === '生成模拟配置' || currentStage === 'generating_config') {
            setPhase(2);
            if (!configTimerRef.current) {
                addLog('开始生成双平台模拟配置...');
                startConfigPolling();
            }
        } else if (currentStage === '准备初始激活事件' || currentStage === 'orchestrating_events') {
            setPhase(3);
        } else if (currentStage === '准备模拟脚本' || currentStage === 'copying_scripts') {
            // 保持阶段，可能在 2 或 3
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [currentStage, addLog]);

    useEffect(() => {
        if (logContentRef.current) {
            logContentRef.current.scrollTop = logContentRef.current.scrollHeight;
        }
    }, [systemLogs.length]);

    return (
        <div className="env-setup-panel">
            {/* 顶层控制栏：暂停/回退/重试防死卡机制 */}
            {phase > 0 && phase < 4 && (
                <div className="env-controls-bar">
                    <span className="control-status-label">
                        {isAborted ? '已中止异常流程' : isPaused ? '已暂停轮询' : '流程执行中...'}
                    </span>
                    <div className="control-btn-group">
                        {!isAborted && !isPaused && (
                            <button className="ctrl-btn pause" onClick={handlePause}>
                                <i className="icon-pause"></i> 暂停轮询
                            </button>
                        )}
                        {!isAborted && isPaused && (
                            <button className="ctrl-btn resume" onClick={handleResume}>
                                <i className="icon-play"></i> 恢复执行
                            </button>
                        )}
                        {isAborted && (
                            <button className="ctrl-btn retry" onClick={handleRetry}>
                                <i className="icon-refresh"></i> 重新开始 (回退重试)
                            </button>
                        )}
                        {!isAborted && (
                            <button
                                className="ctrl-btn abort"
                                onClick={() => handleAbort('用户手工终断')}
                            >
                                <i className="icon-stop"></i> 停止执行
                            </button>
                        )}
                    </div>
                </div>
            )}

            <div className="scroll-container">
                {/* Step 01: 模拟实例 */}
                <div
                    className={`step-card ${phase === 0 ? 'active' : ''} ${phase > 0 ? 'completed' : ''}`}
                >
                    <div className="card-header">
                        <div className="step-info">
                            <span className="step-num">01</span>
                            <span className="step-title">模拟实例初始化</span>
                        </div>
                        <div className="step-status">
                            {phase > 0 ? (
                                <span className="badge success">已完成</span>
                            ) : (
                                <span className="badge processing">初始化</span>
                            )}
                        </div>
                    </div>

                    <div className="card-content">
                        <p className="api-note">POST /api/simulation/create</p>
                        <p className="description">新建simulation实例，拉取模拟世界参数模版</p>
                        {simulationId && (
                            <div className="info-card">
                                <div className="info-row">
                                    <span className="info-label">Project ID</span>
                                    <span className="info-value mono">
                                        {projectData?.project_id}
                                    </span>
                                </div>
                                <div className="info-row">
                                    <span className="info-label">Graph ID</span>
                                    <span className="info-value mono">{projectData?.graph_id}</span>
                                </div>
                                <div className="info-row">
                                    <span className="info-label">Simulation ID</span>
                                    <span className="info-value mono">{simulationId}</span>
                                </div>
                                <div className="info-row">
                                    <span className="info-label">Task ID</span>
                                    <span className="info-value mono">
                                        {taskId || '异步任务已完成'}
                                    </span>
                                </div>
                            </div>
                        )}
                    </div>
                </div>

                {/* Step 02: 生成 Agent 人设 */}
                <div
                    className={`step-card ${phase === 1 ? 'active' : ''} ${phase > 1 ? 'completed' : ''}`}
                >
                    <div className="card-header">
                        <div className="step-info">
                            <span className="step-num">02</span>
                            <span className="step-title">生成 Agent 人设</span>
                        </div>
                        <div className="step-status">
                            {phase > 1 ? (
                                <span className="badge success">已完成</span>
                            ) : phase === 1 ? (
                                <span className="badge processing">{prepareProgress}%</span>
                            ) : (
                                <span className="badge pending">等待</span>
                            )}
                        </div>
                    </div>

                    <div className="card-content">
                        <p className="api-note">POST /api/simulation/prepare</p>
                        <p className="description">
                            结合上下文，自动调用工具从知识图谱梳理实体与关系，初始化模拟个体，并基于现实种子赋予他们独特的行为与记忆
                        </p>

                        {profiles.length > 0 && (
                            <div className="stats-grid">
                                <div className="stat-card">
                                    <span className="stat-value">{profiles.length}</span>
                                    <span className="stat-label">当前Agent数</span>
                                </div>
                                <div className="stat-card">
                                    <span className="stat-value">{expectedTotal || '-'}</span>
                                    <span className="stat-label">预期Agent总数</span>
                                </div>
                                <div className="stat-card">
                                    <span className="stat-value">{totalTopicsCount}</span>
                                    <span className="stat-label">现实种子当前关联话题数</span>
                                </div>
                            </div>
                        )}

                        {profiles.length > 0 && (
                            <div className="profiles-preview">
                                <div className="preview-header">
                                    <span className="preview-title">已生成的 Agent 人设</span>
                                </div>
                                <div className="profiles-list">
                                    {profiles.map((profile, idx) => (
                                        <div
                                            key={idx}
                                            className="profile-card"
                                            onClick={() => setSelectedProfile(profile)}
                                        >
                                            <div className="profile-header">
                                                <span className="profile-realname">
                                                    {profile.profile?.username ||
                                                        profile.username ||
                                                        'Unknown'}
                                                </span>
                                                <span className="profile-username">
                                                    @
                                                    {profile.profile?.name ||
                                                        profile.name ||
                                                        `agent_${idx}`}
                                                </span>
                                            </div>
                                            <div className="profile-meta">
                                                <span className="profile-profession">
                                                    {profile.profile?.profession ||
                                                        profile.profession ||
                                                        '未知职业'}
                                                </span>
                                            </div>
                                            <p className="profile-bio">
                                                {profile.profile?.bio ||
                                                    profile.bio ||
                                                    '暂无简介...'}
                                            </p>
                                            {(
                                                profile.profile?.interested_topics ||
                                                profile.interested_topics
                                            )?.length > 0 && (
                                                <div className="profile-topics">
                                                    {(
                                                        profile.profile?.interested_topics ||
                                                        profile.interested_topics
                                                    )
                                                        .slice(0, 3)
                                                        .map((topic) => (
                                                            <span key={topic} className="topic-tag">
                                                                {topic}
                                                            </span>
                                                        ))}
                                                    {(
                                                        profile.profile?.interested_topics ||
                                                        profile.interested_topics
                                                    ).length > 3 && (
                                                        <span className="topic-more">
                                                            +{' '}
                                                            {(
                                                                profile.profile
                                                                    ?.interested_topics ||
                                                                profile.interested_topics
                                                            ).length - 3}
                                                        </span>
                                                    )}
                                                </div>
                                            )}
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}
                    </div>
                </div>

                {/* Step 03: 生成双平台模拟配置 */}
                <div
                    className={`step-card ${phase === 2 ? 'active' : ''} ${phase > 2 ? 'completed' : ''}`}
                >
                    <div className="card-header">
                        <div className="step-info">
                            <span className="step-num">03</span>
                            <span className="step-title">生成双平台模拟配置</span>
                        </div>
                        <div className="step-status">
                            {phase > 2 ? (
                                <span className="badge success">已完成</span>
                            ) : phase === 2 ? (
                                <span className="badge processing">生成中</span>
                            ) : (
                                <span className="badge pending">等待</span>
                            )}
                        </div>
                    </div>
                    <div className="card-content">
                        <p className="api-note">POST /api/simulation/prepare</p>
                        <p className="description">
                            LLM 根据模拟需求与现实种子，智能设置世界时间流速、推演算法等参数
                        </p>
                        {/* config UI 渲染，为了整洁暂时省略了复杂的配置渲染，在实际应用中需要转化对应的jsx内容 */}
                        {simulationConfig && (
                            <div className="config-detail-panel">{/* ... 配置渲染内容 ... */}</div>
                        )}
                    </div>
                </div>

                {/* Step 04: 初始激活编排 */}
                <div
                    className={`step-card ${phase === 3 ? 'active' : ''} ${phase > 3 ? 'completed' : ''}`}
                >
                    <div className="card-header">
                        <div className="step-info">
                            <span className="step-num">04</span>
                            <span className="step-title">初始激活编排</span>
                        </div>
                        <div className="step-status">
                            {phase > 3 ? (
                                <span className="badge success">已完成</span>
                            ) : phase === 3 ? (
                                <span className="badge processing">编排中</span>
                            ) : (
                                <span className="badge pending">等待</span>
                            )}
                        </div>
                    </div>
                    <div className="card-content">{/* ... Event Orchestration Content ... */}</div>
                </div>

                {/* Step 05: 准备完成 */}
                <div className={`step-card ${phase === 4 ? 'active' : ''}`}>
                    <div className="card-header">
                        <div className="step-info">
                            <span className="step-num">05</span>
                            <span className="step-title">准备完成</span>
                        </div>
                        <div className="step-status">
                            {phase >= 4 ? (
                                <span className="badge processing">进行中</span>
                            ) : (
                                <span className="badge pending">等待</span>
                            )}
                        </div>
                    </div>

                    <div className="card-content">
                        {simulationConfig && autoGeneratedRounds && (
                            <div className="rounds-config-section">
                                <div className="rounds-header">
                                    <div className="header-left">
                                        <span className="section-title">模拟轮数设定</span>
                                    </div>
                                    <label className="switch-control">
                                        <input
                                            type="checkbox"
                                            checked={useCustomRounds}
                                            onChange={(e) => setUseCustomRounds(e.target.checked)}
                                        />
                                        <span className="switch-track"></span>
                                        <span className="switch-label">自定义</span>
                                    </label>
                                </div>

                                {useCustomRounds ? (
                                    <div className="rounds-content custom">
                                        <div className="slider-display">
                                            <div className="slider-main-value">
                                                <span className="val-num">{customMaxRounds}</span>
                                                <span className="val-unit">轮</span>
                                            </div>
                                        </div>
                                        <div className="range-wrapper">
                                            <input
                                                type="range"
                                                value={customMaxRounds}
                                                min="10"
                                                max={autoGeneratedRounds}
                                                step="5"
                                                onChange={(e) =>
                                                    setCustomMaxRounds(Number(e.target.value))
                                                }
                                                className="minimal-slider"
                                                style={{
                                                    '--percent':
                                                        ((customMaxRounds - 10) /
                                                            (autoGeneratedRounds - 10)) *
                                                            100 +
                                                        '%',
                                                }}
                                            />
                                        </div>
                                    </div>
                                ) : (
                                    <div className="rounds-content auto">
                                        <div className="auto-info-card">
                                            <div className="auto-value">
                                                <span className="val-num">
                                                    {autoGeneratedRounds}
                                                </span>
                                                <span className="val-unit">轮</span>
                                            </div>
                                        </div>
                                    </div>
                                )}
                            </div>
                        )}

                        <div className="action-group dual">
                            <button className="action-btn secondary" onClick={onGoBack}>
                                ← 返回图谱构建
                            </button>
                            <button
                                className="action-btn primary"
                                disabled={phase < 4}
                                onClick={handleStartSimulation}
                            >
                                开始双世界并行模拟 ➝
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            {selectedProfile && (
                <div
                    className="profile-modal-overlay"
                    onClick={(e) => {
                        if (e.target === e.currentTarget) setSelectedProfile(null);
                    }}
                >
                    <div className="profile-modal">
                        <div className="modal-header">
                            <div className="modal-header-info">
                                <div className="modal-name-row">
                                    <span className="modal-realname">
                                        {selectedProfile.profile?.username ||
                                            selectedProfile.username}
                                    </span>
                                    <span className="modal-username">
                                        @{selectedProfile.profile?.name || selectedProfile.name}
                                    </span>
                                </div>
                                <span className="modal-profession">
                                    {selectedProfile.profile?.profession ||
                                        selectedProfile.profession}
                                </span>
                            </div>
                            <button className="close-btn" onClick={() => setSelectedProfile(null)}>
                                ×
                            </button>
                        </div>
                        <div className="modal-body">
                            {/* 暂略大部分人设渲染逻辑... */}
                            <div className="modal-section">
                                <span className="section-label">人设简介</span>
                                <p className="section-bio">
                                    {selectedProfile.profile?.bio ||
                                        selectedProfile.bio ||
                                        '暂无简介'}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* Logs View */}
            <div className="system-logs">
                <div className="log-header">
                    <span className="log-title">SYSTEM DASHBOARD</span>
                    <span className="log-id">{simulationId || 'NO_SIMULATION'}</span>
                </div>
                <div className="log-content" ref={logContentRef}>
                    {systemLogs.map((log, idx) => (
                        <div className="log-line" key={idx}>
                            <span className="log-time">{log.time}</span>
                            <span className="log-msg">{log.msg}</span>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};

export default Step2EnvSetup;
